In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np  # 用於設置 NaN 值
import torch
import torch.nn as nn 
import torch.optim as optim
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader

# 檢查是否有 GPU 可用
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("使用的設備:", device)

# path
train_file_path = r"C:\Users\USER\Downloads\NLP-Courses\NLP243\Assignments\HW1_Relation Extraction from Natural Language using PyTorch\hw1_train-1.csv"

# Load the file
train_df = pd.read_csv(train_file_path)

# Fill up the Nan to ""
train_df['CORE RELATIONS'] = train_df['CORE RELATIONS'].fillna('')

# strings into lists
train_df['CORE RELATIONS'] = train_df['CORE RELATIONS'].apply(lambda x: x.split() if isinstance(x, str) else [])
print(train_df.head())


使用的設備: cuda
   ID                                         UTTERANCES  \
0   0               who plays luke on star wars new hope   
1   1                     show credits for the godfather   
2   2             who was the main actor in the exorcist   
3   3  find the female actress from the movie she's t...   
4   4                    who played dory on finding nemo   

                                     CORE RELATIONS  
0  [movie.starring.actor, movie.starring.character]  
1                            [movie.starring.actor]  
2                            [movie.starring.actor]  
3              [movie.starring.actor, actor.gender]  
4  [movie.starring.actor, movie.starring.character]  


In [2]:
# Init the BOW，max_features == 1000
vectorizer = CountVectorizer(max_features=1000)
print(vectorizer)
# UTTERANCES to array
X_train = vectorizer.fit_transform(train_df['UTTERANCES']).toarray()
print(X_train)
# print the shape
# [[0 0 0 ... 0 0 0]
#  [0 0 0 ... 0 0 0]
#  [0 0 0 ... 0 0 0]
#  ...
#  [0 0 0 ... 0 0 0]
#  [0 0 0 ... 0 0 0]
#  [0 0 0 ... 0 0 0]]
print(X_train.shape)  #  (sample, features)(2312, 1000)

CountVectorizer(max_features=1000)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(2312, 1000)


In [3]:
mlb = MultiLabelBinarizer() # have mult-label

y_train = mlb.fit_transform(train_df['CORE RELATIONS']) # label to num arr

print(y_train.shape)  # output = (sample , total label)
print(mlb.classes_)    # label class name


(2312, 19)
['actor.gender' 'gr.amount' 'movie.country' 'movie.directed_by'
 'movie.estimated_budget' 'movie.genre' 'movie.gross_revenue'
 'movie.initial_release_date' 'movie.language' 'movie.locations'
 'movie.music' 'movie.produced_by' 'movie.production_companies'
 'movie.rating' 'movie.starring.actor' 'movie.starring.character'
 'movie.subjects' 'none' 'person.date_of_birth']


In [4]:
# split
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# the size of the dataset
print(X_train.shape, X_val.shape)


(1849, 1000) (463, 1000)


In [5]:
# Data -> PyTorch vector -> move to GPU
X_train_tensor = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).to(device)
X_val_tensor = torch.tensor(X_val, dtype=torch.float32).to(device)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32).to(device)


train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)


In [6]:
# MLP model
class MLPRelationModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(MLPRelationModel, self).__init__()
        self.Layer1 = nn.Linear(input_dim, 256)  # 更新隱藏層大小為 256
        self.Layer2 = nn.Linear(256, 128)        # 更新隱藏層大小為 128
        self.Layer3 = nn.Linear(128, output_dim) # 保持輸出層
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)
    
    def forward(self, x):
        x = self.relu(self.Layer1(x))
        x = self.dropout(x)
        x = self.relu(self.Layer2(x))
        x = self.Layer3(x)
        return x

input_dim = X_train.shape[1]
output_dim = len(mlb.classes_)

# 初始化模型並使用最佳學習率
model = MLPRelationModel(input_dim, output_dim).to(device)
criterion = nn.BCEWithLogitsLoss()  # 使用多標籤損失函數
optimizer = optim.Adam(model.parameters(), lr=0.0027414732532805475)  # 更新學習率


In [8]:
# 訓練模型
for epoch in range(100):  # 更新為最佳 epoch 數量
    model.train()
    running_loss = 0.0
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    avg_loss = running_loss / len(train_loader)
    print(f'Epoch {epoch+1}, Loss: {avg_loss}')


Epoch 1, Loss: 0.2921549354133935
Epoch 2, Loss: 0.16121013963530803
Epoch 3, Loss: 0.08543155753406985
Epoch 4, Loss: 0.048322935652887
Epoch 5, Loss: 0.03140673012440574
Epoch 6, Loss: 0.02215408447102226
Epoch 7, Loss: 0.017137798890150314
Epoch 8, Loss: 0.013702522357122908
Epoch 9, Loss: 0.011387516587876297
Epoch 10, Loss: 0.009739683220435962
Epoch 11, Loss: 0.009051516688236132
Epoch 12, Loss: 0.007960107970324442
Epoch 13, Loss: 0.006100722696985407
Epoch 14, Loss: 0.006755752729830043
Epoch 15, Loss: 0.005715074808465253
Epoch 16, Loss: 0.004543171860357939
Epoch 17, Loss: 0.004158171169772937
Epoch 18, Loss: 0.0033961943112883783
Epoch 19, Loss: 0.0034995958583373256
Epoch 20, Loss: 0.003071722577291878
Epoch 21, Loss: 0.0026913560030716955
Epoch 22, Loss: 0.0032618538037962118
Epoch 23, Loss: 0.002927982298544897
Epoch 24, Loss: 0.0030129072316601104
Epoch 25, Loss: 0.0027421722326584257
Epoch 26, Loss: 0.0025525194793991775
Epoch 27, Loss: 0.002443808639484281
Epoch 28, Lo

In [15]:
# 讀取測試數據
test_file_path = r"C:\Users\USER\Downloads\NLP-Courses\NLP243\Assignments\HW1_Relation Extraction from Natural Language using PyTorch\hw1_test-2.csv"
test_df = pd.read_csv(test_file_path)
X_test = vectorizer.transform(test_df['UTTERANCES']).toarray()
X_test_tensor = torch.tensor(X_test, dtype=torch.float32).to(device)

# 使用模型進行預測
model.eval()
with torch.no_grad():
    outputs = model(X_test_tensor)
    predicted = (torch.sigmoid(outputs) > 0.5).float().cpu()

# 將預測結果轉換為原始標籤格式
predicted_relations = mlb.inverse_transform(predicted.numpy())

# 生成提交文件
submission_df = pd.DataFrame({
    'ID': test_df['ID'],
    'CORE RELATIONS': ['none' if len(relations) == 0 else ' '.join(relations) for relations in predicted_relations]
})

# 保存提交文件
submission_df.to_csv('Final_submission.csv', index=False)
print("提交文件已成功生成，無法預測的行填充為 'none'！")


提交文件已成功生成，無法預測的行填充為 'none'！
